---
- name: Install EPEL
  yum:
    name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
    state: present
  register: install_epel
  until: install_epel|success
  delay: 3
  retries: 5

- name: Install base packages
  yum:
    name:
      - python-pip
    state: latest
    enablerepo: epel-testing
  register: install_base_packages
  until: install_base_packages|success
  delay: 3
  retries: 5

- name: Install Ansible
  pip:
    name:
      - ansible
    state: latest
  register: install_ansible
  until: install_ansible|success
  delay: 3
  retries: 5

- name: get tar for ansibletower
  get_url:
    url: http://releases.ansible.com/ansible-tower/setup-bundle/ansible-tower-setup-bundle-{{ tower_version }}.el7.tar.gz
    dest: /tmp/ansible-tower-setup-bundle-{{ tower_version }}.el7.tar.gz

- name: untar /tmp/ansible-tower-setup-bundle-{{ tower_version }}.el7.tar.gz
  unarchive:
    src: /tmp/ansible-tower-setup-bundle-{{ tower_version }}.el7.tar.gz
    dest: /tmp/
    remote_src: true
    owner: root

- name: replace /tmp/ansible-tower-setup-bundle-{{ tower_version }}.el7/roles/nginx/tasks/tasks.yml
  replace:
    path: /tmp/ansible-tower-setup-bundle-{{ tower_version }}.el7/roles/nginx/tasks/tasks.yml
    regexp: 'CN=localhost'
    replace: "CN={{ ansible_nodename }}"

- name: add /etc/tower path to setting.py
  lineinfile:
    dest: /tmp/ansible-tower-setup-bundle-{{ tower_version }}.el7/roles/awx_install/templates/settings.py.j2
    line: "AWX_PROOT_SHOW_PATHS = ['/etc/tower/']"

- name: copy inventory to setup folder
  template:
    src: templates/towerinventorysetup
    dest: /tmp/ansible-tower-setup-bundle-{{ tower_version }}.el7/inventory

- name: execute the tower installation
  command: /tmp/ansible-tower-setup-bundle-{{ tower_version }}.el7/setup.sh
  register: towerinstall
  until: towerinstall.rc == 0
  retries: 3
  delay: 15
  ignore_errors: yes

- name: change perms on tower.cert
  file:
    path: /etc/tower/tower.cert
    mode: 0444
    group: root
    owner: root

- name: add license
  uri:
    url: https://{{inventory_hostname}}/api/v1/config/
    method: POST
    validate_certs: no
    user: admin
    password: "{{ tower_pass }}"
    status_code: 200
    body: "{{ tower_lic }}"
    body_format: json
  register: add_license
  retries: 10
  until: add_license|success
  ignore_errors: yes
  delay: 5

- name: install pip needed for manageiq-client
  yum:
    name: python2-pip
    state: latest

- name: install manageiq-client
  pip:
    name: manageiq-client

- name: install ansible-tower-cli
  pip:
    name: ansible-tower-cli
    version: 3.1.4

- name: copy tower-cli config /etc/tower/tower_cli.cfg
  template:
    src: templates/tower_cli.cfg.j2
    dest: /etc/tower/tower_cli.cfg
    mode: 0600

- name: fixing satellite6 kind /usr/lib/python2.7/site-packages/tower_cli/resources/credential.py
  template:
    src: credential.py
    dest: /usr/lib/python2.7/site-packages/tower_cli/resources/credential.py
    mode: 0644
    owner: root
    group: root

# see https://github.com/ansible/ansible/pull/31760
- name: fixing cloudforms inventory script
  template:
    src: cloudforms.py
    dest: /var/lib/awx/venv/awx/lib/python2.7/site-packages/awx/plugins/inventory/cloudforms.py
    mode: 0755
    owner: root
    group: root
