- name: get record for router ELB DNS Entry
  route53:
    command: get
    zone: "{{ hosted_zone_domain_name }}"
    record: "{{ ec2_name_prefix }}.{{ hosted_zone_domain_name }}"
    type: A
  register: routerelbrec
  when: hosted_zone_domain_name is defined and ec2_name_prefix is defined
  delegate_to: 127.0.0.1
  become: no

- name: create Router ELB DNS Entry if it doesn't exist
  route53:
    command: create
    overwrite: yes
    zone: "{{ hosted_zone_domain_name }}"
    record: "{{ ec2_name_prefix }}.{{ hosted_zone_domain_name }}"
    type: A
    value: "{{ inventory_hostname }}"
  when: routerelbrec.set is defined and "{} == routerelbrec.set"
  delegate_to: 127.0.0.1
  become: no