---

- name: Delete demo inventory
  uri:
    url:  https://localhost/api/v2/inventories/1/
    method: DELETE
    user: admin
    password: "{{ tower_pass }}"
    validate_certs: False
    status_code:
      - 200
      - 201
      - 202
      - 204
      - 400
      - 404
  register: response
  changed_when: response.status == 204

- name: Delete demo project
  uri:
    url:  https://localhost/api/v2/projects/4/
    method: DELETE
    user: admin
    password: "{{ tower_pass }}"
    validate_certs: False
    status_code:
      - 200
      - 201
      - 202
      - 204
      - 400
      - 404
  register: response
  changed_when: response.status == 204

- name: Delete demo template
  uri:
    url:  https://localhost/api/v2/job_templates/5/
    method: DELETE
    user: admin
    password: "{{ tower_pass }}"
    validate_certs: False
    status_code:
      - 200
      - 201
      - 202
      - 204
      - 400
      - 404
  register: response
  changed_when: response.status == 204

- name: Delete demo credential
  uri:
    url:  https://localhost/api/v2/credentials/1/
    method: DELETE
    user: admin
    password: "{{ tower_pass }}"
    validate_certs: False
    status_code:
      - 200
      - 201
      - 202
      - 204
      - 400
      - 404
  register: response
  changed_when: response.status == 204

- name: create inventory
  uri:
    url:  https://localhost/api/v2/inventories/
    method: POST
    user: admin
    password: "{{ tower_pass }}"
    body: "{{ lookup('file','tower_inventory.json') }}"
    body_format: json
    validate_certs: False
    status_code:
      - 200
      - 201
      - 400
  register: response
  changed_when: response.status == 201

- name: create group
  uri:
    url:  https://localhost/api/v2/groups/
    method: POST
    user: admin
    password: "{{ tower_pass }}"
    body: "{{ lookup('template','tower_group.json.j2') }}"
    body_format: json
    validate_certs: False
    status_code:
      - 200
      - 201
      - 400
  register: response
  changed_when: response.status == 201

- name: create host
  uri:
    url:  https://localhost/api/v2/hosts/
    method: POST
    user: admin
    password: "{{ tower_pass }}"
    body: "{{ lookup('template','tower_host.json.j2') }}"
    body_format: json
    validate_certs: False
    status_code:
      - 200
      - 201
      - 400
  register: response
  changed_when: response.status == 201

- name: Associate host to group
  uri:
    url:  https://localhost/api/v2/groups/1/hosts/
    method: POST
    user: admin
    password: "{{ tower_pass }}"
    body: '{ "id": 2 }'
    body_format: json
    validate_certs: False
    status_code:
      - 200
      - 204
      - 400
  register: response
  changed_when: response.status == 204

- name: Add win_shell/win_feature/win_reboot to allowed adhoc modules
  uri:
    url:  https://localhost/api/v2/settings/all/
    method: PATCH
    user: admin
    password: "{{ tower_pass }}"
    body: "{{ lookup('template','tower_config_adhoc.json.j2') }}"
    body_format: json
    validate_certs: False
    status_code:
      - 200
      - 204
      - 400
  register: response
  changed_when: response.status == 200

- name: Disable GIT Cert validation
  lineinfile:
    path: /etc/tower/settings.py
    regexp: 'GIT_SSL_NO_VERIFY'
    line: "AWX_TASK_ENV['GIT_SSL_NO_VERIFY'] = 'True'"
  notify: restart tower
