---
- name: Add Amazon EC2 Provider to ManageIQ
  manageiq_provider:
    name: 'AWS01'
    provider_type: 'amazon'
    state: 'present'
    provider_region: 'us-east-1'
    access_key_id: "{{ student_ec2_access }}"
    secret_access_key: "{{ student_ec2_secret }}"
    miq_url: 'https://{{ inventory_hostname }}'
    miq_username: 'admin'
    miq_password: "{{ cfme_pass }}"
    miq_verify_ssl: false
  become: false
  delegate_to: localhost
  register: result
  retries: 10
  until: result|success
  ignore_errors: yes
  delay: 5

- debug: var=result
